name: Testing

on: [push, pull_request]

jobs:
  lint:
    if: github.repository == 'openkim/kimvv'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: pip install pre-commit
      - name: Lint
        run: pre-commit run --show-diff-on-failure --all-files

  test:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-15, macos-15-intel]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up micromamba
        uses: mamba-org/setup-micromamba@v1.9.0
        with:
          environment-name: test-env
          cache-environment: true
          create-args: >-
            -f test/environment.yml

      - name: Install units and AFLOW on Linux
        if: runner.os == 'Linux'
        shell: bash -el {0}
        run: |
          sudo apt-get update
          sudo apt-get -y install units
          wget https://github.com/aflow-org/aflow/releases/download/v4.0.5/aflow-4.0.5-ubuntu22-amd64.tar.gz
          tar -xf aflow-4.0.5-ubuntu22-amd64.tar.gz

      - name: Install units and AFLOW on macOS
        if: runner.os == 'macOS'
        shell: bash -el {0}
        run: |
          brew tap aflow-org/aflow
          brew install aflow
          brew install gnu-units

      - name: Run pre-setup and install
        shell: bash -el {0}
        run: |
          python pre_setup.py
          # Install kimvv only into a special directory that we make unwriteable to mimic a system install
          # This is to make sure test drivers don't need to write to their own files to run
          mkdir local-python
          python -m pip install . -t local-python --no-deps
          chmod -R -w local-python

          # Now install any dependencies normally. If we install without --no-deps
          # above, it would install ALL dependencies, including reinstalling
          # stuff that already exists in the conda env
          echo "PYTHONPATH=$PYTHONPATH:$PWD/local-python" >> "$GITHUB_ENV"
          python -c "from importlib.metadata import requires; print(' '.join(requires('kimvv')))" | xargs python -m pip install


      - name: Run tests
        shell: bash -el {0}
        run: |
          export PATH=$PATH:$PWD/aflow-4.0.5-Linux/bin
          cd test
          pytest
